name = "prompt-instructions-mcp-pure"
main = "src/pure-mcp-index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 database for instruction sets
[[d1_databases]]
binding = "DB"
database_name = "travel_assistant"
database_id = "e6723f99-1d99-45bb-a941-e7600a56abe9"

# KV namespace for prompt caching (disabled due to API token permissions)
# [[kv_namespaces]]
# binding = "PROMPTS_CACHE"
# id = "012c2dd8c3d64b62bf211ca65d2ae860"

[observability.logs]
enabled = true

[vars]
MCP_AUTH_KEY = "prompt-instructions-mcp-auth-key-2025"

[triggers]
crons = []