name = "basic-memory-mcp-pure"
main = "src/pure-mcp-index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV namespace for knowledge storage
[[kv_namespaces]]
binding = "BASIC_MEMORY_KV"
id = "88bd0ef6b5304d06b61b291aa3319ee8"

[observability.logs]
enabled = true

[vars]
MCP_AUTH_KEY = "basic-memory-mcp-auth-key-2025"

[triggers]
crons = []