# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD013/line-length - Line length (disabled in pre-commit)
MD013: false

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 0  # Allow content immediately after headings

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;!？。，；！"  # Allow colons in headings

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: false  # Disable - too restrictive for documentation

# MD033/no-inline-html - Inline HTML (disabled in pre-commit)
MD033: false

# MD034/no-bare-urls - Bare URL used
MD034: false  # Allow bare URLs in documentation

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false  # Not always practical

# Allow trailing spaces (sometimes needed for line breaks)
MD009: false

# Allow multiple spaces after blockquote symbol
MD027: false

# Allow multiple spaces after hash on atx style heading
MD019: false

# Allow spaces inside emphasis markers
MD036: false

# Allow spaces inside link text
MD039: false

# MD029/ol-prefix - Ordered list item prefix
MD029: false  # Allow flexible numbering in ordered lists

# MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: false  # Too restrictive for documentation

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: false  # Not critical for documentation

# MD004/ul-style - Unordered list style
MD004: false  # Allow mix of * and - for lists

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012: false  # Sometimes useful for visual separation

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: false  # Not always necessary for examples
