repos:
  - repo: local
    hooks:
      - id: claude-md-validation
        name: Validate CLAUDE.md structure
        entry: scripts/validate-claude-md.sh
        language: system
        files: CLAUDE\.md$
        pass_filenames: false
        always_run: false

      - id: documentation-sync
        name: Sync documentation with codebase changes
        entry: scripts/sync-docs.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Temporarily disabled - causing commit issues
      # - id: trailing-whitespace
      #   exclude: '\.md$'
      # - id: end-of-file-fixer
      #   exclude: '\.md$'
      - id: check-yaml
        exclude: 'wrangler\.toml$'
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Markdownlint disabled - too strict for personal project docs
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.42.0
  #   hooks:
  #     - id: markdownlint
  #       files: '\.md$'
  #       args: ['--disable', 'MD013', 'MD033', '--']
