# Wrangler configuration for Pure R2 Storage MCP Worker
name = "r2-storage-mcp-pure"
main = "src/pure-mcp-index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Enable logs for debugging
[observability.logs]
enabled = true

# Associate R2 buckets with your Worker
[[r2_buckets]]
binding = "TRAVEL_MEDIA_BUCKET"  # Primary binding
bucket_name = "travel-media"     # Your actual bucket name

[vars]
MCP_AUTH_KEY = "r2-mcp-auth-key-2025"

[dev]
port = 8102
host = "localhost"

[triggers]
crons = []

# Environment-specific configurations
[env.staging]
name = "r2-storage-mcp-pure-staging"
route = { pattern = "r2-storage-mcp-pure-staging.somotravel.workers.dev", custom_domain = false }
usage_model = "bundled"

[env.production]
name = "r2-storage-mcp-pure" 
route = { pattern = "r2-storage-mcp-pure.somotravel.workers.dev", custom_domain = false }
usage_model = "bundled"