name = "sequential-thinking-pure"
main = "src/pure-mcp-index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "sequential-thinking-pure"
routes = [
  { pattern = "sequential-thinking-mcp-pure.somotravel.workers.dev", zone_name = "somotravel.com" }
]

[observability.logs]
enabled = true

[vars]
MCP_AUTH_KEY = "sequential-thinking-auth-2025"

[triggers]
crons = []