// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
	interface Env {
		CACHE: KVNamespace;
		AMADEUS_API_KEY: string;
		AMADEUS_API_SECRET: string;
		MCP_AUTH_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
