name = "github-mcp-pure"
main = "src/pure-mcp-index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[vars]
MCP_AUTH_KEY = "github-mcp-auth-key-2025"

# Secrets (set via wrangler secret put)
# GITHUB_TOKEN = "..."

[triggers]
crons = []