name = "github-mcp-pure"
main = "src/pure-mcp-index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
environment = "production"
# Note: GITHUB_TOKEN and MCP_AUTH_KEY should be set via environment variables
# or wrangler secrets for production deployment

[env.production]
name = "github-mcp-pure"
route = { pattern = "github-mcp-pure.somotravel.workers.dev/*", zone_name = "somotravel.workers.dev" }

[env.staging]
name = "github-mcp-staging"