name = "travel-document-generator-mcp-pure"
main = "src/pure-mcp-index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 database for document templates and trip data
[[d1_databases]]
binding = "DB"
database_name = "travel_assistant"
database_id = "e6723f99-1d99-45bb-a941-e7600a56abe9"

# R2 bucket for image storage
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "travel-media"

[observability.logs]
enabled = true

[vars]
MCP_AUTH_KEY = "travel-document-generator-mcp-auth-key-2025"
R2_URL_BASE = "https://r2-storage-mcp.somotravel.workers.dev"
BASE_URL = "https://somotravel.com"
REPO_OWNER = "somo-travel"
REPO_NAME = "travel-documents"

# Secrets (set via wrangler secret put)
# GOOGLE_MAPS_API_KEY = "..."
# GITHUB_TOKEN = "..."

[triggers]
crons = []