name = "d1-database-robust"
main = "src/robust-mcp-index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# D1 database for travel data
[[d1_databases]]
binding = "DB"
database_name = "travel_assistant"
database_id = "e6723f99-1d99-45bb-a941-e7600a56abe9"

[observability.logs]
enabled = true

[vars]
MCP_AUTH_KEY = "robust-d1-auth-2025"

[triggers]
crons = []